openapi: 3.1.1
info:
  title: API de exemplo do instagram
  description: Uma api de teste
  version: 0.0.1

tags:
  - usuários
  - Postagens
  - Comentários
  - Post
  - Curtida


paths:
  /api/usuarios:
    get:
      tags: 
        [Usuarios]
    post:
    patch:
    delete:
  
  /api/usuario/:id:
    get:
    patch:
    delete:


components:
  schemas:
    Usuario:
      type: object
      properties:
        id:
          type: integer
          example: 1
        nome: 
          type: string
          example: Chico Cesar
          nulllable: false


